### ISSUE TITLE
Improved 404 page

### ISSUE THREAD

**Issue by Sothatsit** [Sothatsit/RoyalUrClient#122]
Currently the 404 page is incredibly basic. It works, but it would be nice for it to be a little nicer...

The file that contains the HTML of the 404 page is at [client/html/lost.html](https://github.com/Sothatsit/RoyalUrClient/blob/master/client/html/lost.html).

**The current 404 page:**
![404](https://user-images.githubusercontent.com/1185881/108474239-0fdc7b00-72ca-11eb-973d-87de765543fb.png)

**Comment by frostzt** [comment]
I've created a bit better one, not so good but you might wanna check it out! It is composed of inline styles. I am a bit confused with how your site works for CSS files and their compilation!

**Comment by Sothatsit** [comment]
Thankyou @frostzt!
