### ISSUE TITLE
Play a friend not loading 

### ISSUE THREAD

**Issue by silverhand2077** [Sothatsit/RoyalUrClient#129]
**Describe the Bug:** \
Upon sending a game invite to a friend, the game is unable to load. This is a new issue as last evening I didn't experience this problem.

**Steps to Reproduce:** \
Create a Friend game, and open the link in a new tab. The page will never leave the loading screen.

**Comment by Sothatsit** [comment]
Thanks for reporting this, I can reproduce this bug. I'll try fix it asap!

**Comment by Sothatsit** [comment]
This should now be fixed, thanks for reporting this bug!
