### ISSUE TITLE
Websocker server TLS cert expired

### ISSUE THREAD

**Issue by coderanger** [Sothatsit/RoyalUrClient#175]
The LetsEncrypt cert used on https://royalur.net:9113/ has expired. I'm guessing it's the same actual cert as the main site but the app handling websockets hasn't been reloaded in 90 days.

**Comment by Sothatsit** [comment]
Thanks for the heads up! I have restarted the server now, is that all that is needed to fix the TLS certificate?

**Comment by coderanger** [comment]
Looks good now! `Expiration Date: February 13, 2022`. If you would like help setting up some basic monitoring, I want walk you through doing a free Uptime Robot account :)

**Comment by Sothatsit** [comment]
That would be great! I've now created a free account on Uptime Robot

**Comment by coderanger** [comment]
I'll jump in Discord and can help you with the setup :)
