### ISSUE TITLE
Display the reason for no moves as well

### ISSUE THREAD

**Issue by Sothatsit** [Sothatsit/RoyalUrClient#59]
It can be confusing when you just get a "No Moves" message if you don't know why. I think a subtitle under the No Moves with the reason for it would help this issue.

Could be two reasons:
1) Rolled a zero
2) All moves blocked

**Comment by Phyrik** [comment]
Started work on this [with this commit](https://github.com/Phyrik/RoyalUrClient/commit/80741d2b230f982d9f0e28bca94c300cac4c5297) over at my fork.

Is there already a way to have a subtitle in that overlay screen or is that something we'd have to add?

**Comment by Sothatsit** [comment]
> Started work on this [with this commit](https://github.com/Phyrik/RoyalUrClient/commit/80741d2b230f982d9f0e28bca94c300cac4c5297) over at my fork.
> 
> Is there already a way to have a subtitle in that overlay screen currently or is that something we'd have to add?

Hey, thankyou for this! There isn't currently any way to display the subtitles. I am planning to fix that today though! My current plan is to update the `setMessage` function to take a subtitle as well, like: `setMessage(message, submessage, ...)`. Then, we just have to make a small change to your changes so that it uses the new `setMessage` 😃

Might also have a play around with the text for the reason as well to see what makes the most sense and fits the best. Currently I was thinking:
- "You rolled a zero", and
- "All moves blocked"

What do you think?

**Comment by Sothatsit** [comment]
The reason sent to the client along with the "No moves" has also now been updated by [RoyalUrServer#92fd79b](https://github.com/Sothatsit/RoyalUrServer/commit/92fd79b14067c84025a0d2c7fcd3e0a7211aefbd).

**Comment by Sothatsit** [comment]
I think as of #78 and [d5a5735](https://github.com/Sothatsit/RoyalUrClient/commit/d5a57353a94ff5d56bac52c874b396e513002d74), all cases where no moves could occur are now accompanied by a reason!
