### ISSUE TITLE
Add a privacy policy and cookie acceptance banner

### ISSUE THREAD

**Issue by Sothatsit** [Sothatsit/RoyalUrClient#60]
I have no clue if this is GDPR compliant. The website might need one of those accept cookies banners at the bottom of the screen.

**Comment by pludi** [comment]
Checked. GDPR isn't about the Cookie Banners by the way, that's the [ePrivacy Directive](https://en.wikipedia.org/wiki/Privacy_and_Electronic_Communications_Directive_2002#Cookies), but as you don't set any cookies you're fine with that as soon as the Google Tag Manager is removed.

What you'd need to comply with the GDPR would be a Privacy Policy on which data you collect and for what reasons and how long (eg. IP addresses are saved for 7 days to protect against attacks), as well as a point of contact for users to request their information (see https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Rights_of_the_data_subject)

**Comment by Sothatsit** [comment]
> Checked. GDPR isn't about the Cookie Banners by the way, that's the [ePrivacy Directive](https://en.wikipedia.org/wiki/Privacy_and_Electronic_Communications_Directive_2002#Cookies), but as you don't set any cookies you're fine with that as soon as the Google Tag Manager is removed.
> 
> What you'd need to comply with the GDPR would be a Privacy Policy on which data you collect and for what reasons and how long (eg. IP addresses are saved for 7 days to protect against attacks), as well as a point of contact for users to request their information (see https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Rights_of_the_data_subject)

Oh great, thankyou very much for helping me out with that! Do you mean that I'd need to remove the Google Analytics to comply with the ePrivacy Directive? I'll have a better look into getting a proper privacy policy and hosting it. Thanks again for the help!

**Comment by pludi** [comment]
Either remove Google Analytics, or add the Cookie Banner which has to be Opt-In to be valid.

As for the Privacy Policy, it doesn't have to be legalese. Article 12 (1)[even states that]

> The controller shall take appropriate measures to provide any information referred to in Articles 13 and 14 and any communication under Articles 15 to 22 and 34 relating to processing to the data subject in a concise, transparent, intelligible and easily accessible form, using clear and plain language, in particular for any information addressed specifically to a child.

So just write up some bullet points for each data point you collect, why you collect them, and how long they're saved. Add them after a paragraph explaining the rights of the user (right to access under Article 15, rectification Article 16, …) and you're good.

**Comment by Sothatsit** [comment]
> Either remove Google Analytics, or add the Cookie Banner which has to be Opt-In to be valid.
> 
> As for the Privacy Policy, it doesn't have to be legalese. Article 12 (1)[even states that]
> 
> > The controller shall take appropriate measures to provide any information referred to in Articles 13 and 14 and any communication under Articles 15 to 22 and 34 relating to processing to the data subject in a concise, transparent, intelligible and easily accessible form, using clear and plain language, in particular for any information addressed specifically to a child.
> 
> So just write up some bullet points for each data point you collect, why you collect them, and how long they're saved. Add them after a paragraph explaining the rights of the user (right to access under Article 15, rectification Article 16, …) and you're good.

Perfect, thankyou very much!

For future reference, we collect:
- User IP addresses, time of accessing the page, and their user agent in the Apache server logs
- Any data that the Google Analytics stores, although it might be good to remove this!

**Comment by Sothatsit** [comment]
I think we should switch to using an analytics tool such as https://usefathom.com/, which doesn’t set cookies, and collects much less information which is good because we don’t need that much.

**Comment by Sothatsit** [comment]
As of [93b991b](https://github.com/Sothatsit/RoyalUrClient/commit/93b991ba78606a1985cbcdf1e7cca9462fcaddad) we now use self-hosted Matomo analytics, and the Google Analytics has been removed from the site.

**Comment by Sothatsit** [comment]
A privacy policy has now been added as of [e4563b0](https://github.com/Sothatsit/RoyalUrClient/commit/e4563b01e80d5c8c61448bee2c79880b291be6e8), which is hosted at https://royalur.net/privacy.

@pludi, if you had a spare moment I'd really appreciate it if you could look over it and make sure its all good :)

**Comment by pludi** [comment]
Looks good as far as I can tell!

**Comment by Sothatsit** [comment]
> Looks good as far as I can tell!

Awesome, thanks!
