### ISSUE TITLE
Make sound when online twoplayer game connects

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#65]
Hi. Love the game, thank you!

Searching for an online game to connect to can take quite a while. In the meantime you probably start doing something else, and might not notice that the game have started. It would be very helpful if there was a sound when the game started.

Thanks!

**Comment by Sothatsit** [comment]
Thanks for the suggestion! I think this is a great idea. Might be able to repurpose the sound of landing on a rosette for this, as I plan to replace that sound in the near future.

**Comment by Sothatsit** [comment]
This was added in [b8c03ce](https://github.com/Sothatsit/RoyalUrClient/commit/b8c03ceda2ca9d8f4018042b431a4bdc54b602df), although note the sound doesn't play if the tab is minimised unfortunately. Not sure if there is a way to get around not being able to play a sound while a tab isn't open.

**Comment by forteller** [comment]
Thank you! But there has to be a way for sound to play even when the tab is not in front. I do that all the time with YouTube, Twitter etc. I don't know how, though.

**Comment by Sothatsit** [comment]
> Thank you! But there has to be a way for sound to play even when the tab is not in front. I do that all the time with YouTube, Twitter etc. I don't know how, though.

Good point, this would be a very nice change.

**Comment by Sothatsit** [comment]
Turns out this was due to the code that plays sound that I wrote intentionally not playing sounds when the tab is not active! An exception for the game notification sound has been added in [8096ac0](https://github.com/Sothatsit/RoyalUrClient/commit/8096ac0b19f9adf047c0106ebaf54f0f9182d0fe).

**Comment by forteller** [comment]
Amazing, thank you! :)
