### ISSUE TITLE
Keyboard on menu screen

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#66]
I love so much that all you need to play is the space bar and enter key! But it would also be great if you could use the keyboard in the menu. The tiles on each side of the "play" button makes it seem like you can move them up and down with the arrow keys and press enter/space to select the button, but you can't. That's a bit confusing.

**Comment by Sothatsit** [comment]
This would be really cool! It is quite low priority for me though, as there's a lot of other changes that I think would impact the user experience on the site more to make in the meantime. Thanks for the suggestion though, hopefully eventually it gets added!

**Comment by forteller** [comment]
Totally understandable! In the mean time, maybe remove the tiles, as to not give the wrong impression? :)

**Comment by Sothatsit** [comment]
> Totally understandable! In the mean time, maybe remove the tiles, as to not give the wrong impression? :)

I actually quite like the tiles there just to give more focus onto the play button, and make the menu less bland. That was the original intention of adding them there. Without them, the wood colour becomes a bit overwhelming in my opinion.

**Comment by Sothatsit** [comment]
This isn't really relevant as of #126.
