### ISSUE TITLE
Move key on both sides of the keyboard

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#69]
Again: I love that you can play with just the keyboard! I want to suggest that instead of just moving with Enter, you also add a move button on the left side of the keyboard. 

I would suggest A, or maybe even all of Q, W, A and S, to make the area you can hit similarly sized as the area you can hit on the right side.

Two reasons:
1. For left handed people
2. When you play local two player one player might sit to the left of the computer. Instead of having to stretch all the way over to Enter, it would be a lot easier to press a key on the left side.

Thanks again!

**Comment by Sothatsit** [comment]
The letter "Q" was added as an alternative to enter as part of the commit [9065da9](https://github.com/Sothatsit/RoyalUrClient/commit/9065da97617e94521c677f7bbe5c1c1a83492e5b).
