### ISSUE TITLE
Online two player with specific person

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#70]
I understand that this would be a lot of work, but it would also make the website so much greater than it already is. The ability to play against a specific friend over the internet would especially be appreciated during these lockdown times.

No worries if you feel this is out of scope or just too much to ask! It's just something I'd really love to see! :)

**Comment by Sothatsit** [comment]
This has a related issue [RoyalUrServer#3](https://github.com/Sothatsit/RoyalUrServer/issues/3) about implementing this same feature 👍

**Comment by Sothatsit** [comment]
The issue #52 is also related to this, as that issue contains suggestions for how the UI of this change would be implemented.

**Comment by Sothatsit** [comment]
This has been added in [ab582e4](https://github.com/Sothatsit/RoyalUrClient/commit/ab582e418975fd07fe9b19dec114011ebe3a8984)!

**Comment by forteller** [comment]
Amazing! Thank you! :D
