### ISSUE TITLE
Dismiss "no moves" screen with space bar

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#72]
Title says it all :)

**Comment by Sothatsit** [comment]
This has been added in [9065da9](https://github.com/Sothatsit/RoyalUrClient/commit/9065da97617e94521c677f7bbe5c1c1a83492e5b).

**Comment by forteller** [comment]
Thank you again for your amazing speed at replying to all my requests and implementing them! I'm so happy about that!

One thing about this, though: The reason I wanted to dismiss the "no moves" screen was to keep on playing asap. But now, even when dismissing the screen, it still takes just as long as before for the dice to show up and be ready to roll again. This is possibly even more frustrating than before, because you expect to be able to roll again when the screen has been dismissed. If it would be possible to make sure that any press of the space bar after the screen is gone rolls the dice, that would be fantastic! Thanks!

**Comment by Sothatsit** [comment]
> Thank you again for your amazing speed at replying to all my requests and implementing them! I'm so happy about that!
> 
> One thing about this, though: The reason I wanted to dismiss the "no moves" screen was to keep on playing asap. But now, even when dismissing the screen, it still takes just as long as before for the dice to show up and be ready to roll again. This is possibly even more frustrating than before, because you expect to be able to roll again when the screen has been dismissed. If it would be possible to make sure that any press of the space bar after the screen is gone rolls the dice, that would be fantastic! Thanks!

This is a very good point! I've created an issue for addressing this now, which you can see at #81.

Also I just have to say a massive thankyou to you for all of the amazing suggestions and attention to detail that you've been putting in to the game! The game is much nicer to play now thanks to your help!

**Comment by forteller** [comment]
I love giving feedback on great products, especially when I'm listened to, and it gets fixed so fast! :D Thank you for the kind words, I'm so happy you appreciate it! :)
