### ISSUE TITLE
"You rolled a zero" – online game

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#88]
If the other player rolls a zero in an online game, it still says "you rolled a zero". Maybe it should say "Dark" or "They" or something? :)

**Comment by Sothatsit** [comment]
> If the other player rolls a zero in an online game, it still says "you rolled a zero". Maybe it should say "Dark" or "They" or something? :)

There's actually already an issue for this in RoyalUrServer :) https://github.com/Sothatsit/RoyalUrServer/issues/13
